//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGINTB
    {
        public int IDLOGIN { get; set; }
        public string USEREMAIL { get; set; }
        public string USERPASSWORD { get; set; }
    }
}
