//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBVideoLocadoraEntities : DbContext
    {
        public DBVideoLocadoraEntities()
            : base("name=DBVideoLocadoraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GENRETB> GENRETB { get; set; }
        public virtual DbSet<MOVIETB> MOVIETB { get; set; }
        public virtual DbSet<LOGINTB> LOGINTB { get; set; }
        public virtual DbSet<LOCATIONTB> LOCATIONTB { get; set; }
        public virtual DbSet<MOVIEXLOCATION> MOVIEXLOCATION { get; set; }
    }
}
