//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIETB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOVIETB()
        {
            this.MOVIEXLOCATION = new HashSet<MOVIEXLOCATION>();
        }
    
        public int IDMOVIE { get; set; }
        public string NAMEMOVIE { get; set; }
        public Nullable<System.DateTime> CREATIONDATE { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public Nullable<int> IDGENRE { get; set; }
    
        public virtual GENRETB GENRETB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIEXLOCATION> MOVIEXLOCATION { get; set; }
    }
}
