//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIEXLOCATION
    {
        public int ID { get; set; }
        public Nullable<int> IDLOCATION { get; set; }
        public Nullable<int> IDMOVIE { get; set; }
    
        public virtual LOCATIONTB LOCATIONTB { get; set; }
        public virtual MOVIETB MOVIETB { get; set; }
    }
}
